name: demo_back_sms
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  background_sms: ^0.0.4
  permission_handler: ^11.0.0
  geolocator: ^10.1.0
  fluttertoast: ^8.2.2
  sqflite: ^2.3.0
  flutter_speed_dial: ^7.0.0
  easy_localization: ^3.0.3
  shared_preferences: ^2.2.2
  provider: ^6.0.5
  internet_connection_checker: ^1.0.0+1
  connectivity_plus: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/translations/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #